[package]
name = "blacknote"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "blacknote"
crate-type = ["cdylib", "staticlib"]

[dependencies]
uniffi = { version = "0.28", features = ["build", "tokio", "cli"] }
pulldown-cmark = { version = "0.10", default-features = false }
rusqlite = { version = "0.31", features = ["bundled"] }
parking_lot = "0.12"
thiserror = "1"

[build-dependencies]
uniffi = { version = "0.28", features = ["build"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
