org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8 -XX:+UseParallelGC -Dcom.android.ddmlib.shell.timeoutms=120000 -Dcom.android.ddmlib.shell.max-time-to-output-response=120000
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false
org.gradle.daemon=true
kotlin.incremental=true
ksp.incremental=true
android.builtInKotlin=false
android.newDsl=false
org.gradle.configuration-cache=true
